# Generated by Django 5.1.4 on 2024-12-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tickets_event_remove_tickets_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reserved_until',
        ),
    ]
